POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "userName": "aylin",
  "email": "aylin@gmail.com",
  "password": "123456"
}
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "aylin@gmail.com",
  "password": "123456"
}

###
POST http://localhost:3000/comments
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN

{
  "postId": "69ecf105835bbb0f60042eba",
  "content": "my first comment"
}

###
POST http://localhost:3000/ai/caption
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN

{
  "content": "I started learning React today and built my first component"
}